### ISSUE TITLE
sm_setclass clash with [TF2 Set Class]

### ISSUE THREAD

**Issue by ZeronTheXeon** [EasyEorsak/EventManager#1]
Problem: sm_setclass clashes with https://forums.alliedmods.net/showthread.php?p=1333506

Steps to Reproduce:
1. Run the plugin with https://forums.alliedmods.net/showthread.php?p=1333506, ya dum.

Solution: Add a sm_event_ or sm_e prefix to all commands to prevent clashing.

**Comment by eaasye** [comment]
sm_setclass has been changed to sm_eclass. Sorry for late reply, was on vacation when issue was opened.
